#! /bin/sh

# Uncomment these if the dual monitor is enabled
# bspc monitor DP-4 -d TTY DEF DEV WEB MED
# bspc monitor HDMI-0 -d TTY DEF DEV WEB MED

### Single Monitor set up ###
# Uses the default desktop and gives it the 5 desktops
# bspc monitor -d TTY DEF DEV WEB MED
bspc monitor -d 1 2 3 4 5 6 7 8

### BSPWM Settings ###

# BORDER SETTINGS
bspc config border_width        3
bspc config normal_border_color "#4c566a"
bpsc config active_border_color "#1e1e1e"
bspc config focused_border_color "#546e7a"
bspc config presele_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# CURSOR SETTINGS 
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# MISC SETTINGS
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config window_gap          10

### BSPWM Window Rules ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Surf state=tiled
bspc rule -a Zathura state=pseudo_tiled
bspc rule -a Picture-in-Picture state=tiled

### Autostart Apps ###

# Set wallpaper
nitrogen --restore &

# Set cursor to left pointer when just pointing at the wallpaper
xsetroot -cursor_name left_ptr &

# Launches the compositor
# in my case the ibhagwan fork as it provides rounded corners and blur
picom &

# Launches my keybinds daemon
sxhkd &

# Launches my topbar and kills any that are already running
/home/$USER/.config/polybar/launch.sh &
