#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun,window -show drun -sidebar-mode -line-padding 4 -columns 1  -width 10 -padding 30 -hide-scrollbar -show-icons -drun-icon-theme "Papirus-Dark"
