#!/bin/bash

## Created By Aditya Shakya

# rofi -modi run,drun -show drun -location 7 -xoffset 12 -yoffset -676 -line-padding 4 -columns 1 -width 20 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme -theme sidebar
rofi -modi run,drun -show drun -line-padding 4 -columns 3 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme -theme .config/polybar/scripts/themes/nordic_sidebar.rasi
